Repository 2024-ITShow-MToM/MtoM-Back, pull requests merged in 2024-05, with the labels that each got.

#3 :tada: [Feat] (#2) 프로젝트 시작
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/MtoM/MtoM/MtoMApplication.java
  src/main/resources/application.properties
  src/test/java/com/MtoM/MtoM/MtoMApplicationTests.java
Labels: 💡 Enhancement

#8 ✨ [Feat] (#6) CORS 설정을 위한 WebConfig 클래스 추가
  src/main/java/com/MtoM/MtoM/domain/conifg/WebConfig.java
Labels: 💡 Enhancement

#18 🐛 [fix] 머지 에러 수정
  src/main/java/com/MtoM/MtoM/domain/qna/post/controller/PostController.java
  src/main/java/com/MtoM/MtoM/domain/qna/post/domain/PostEntity.java
  src/main/java/com/MtoM/MtoM/domain/qna/post/repository/PostRepository.java
  src/main/java/com/MtoM/MtoM/domain/qna/post/service/PostService.java
Labels: 🐞 Bugfix

#32 ✨ [Feat] (#7) QNA 게시판, 양자택일 CRUD API 구현
  .gitignore
  src/main/java/com/MtoM/MtoM/domain/qna/post_comment/domain/PostCommentDomain.java
  src/main/java/com/MtoM/MtoM/domain/qna/post_comment/repository/PostCommentRepository.java
  src/main/java/com/MtoM/MtoM/domain/qna/posts/controller/PostController.java
  src/main/java/com/MtoM/MtoM/domain/qna/posts/domain/PostDomain.java
  src/main/java/com/MtoM/MtoM/domain/qna/posts/dto/CreatePostDTO.java
  src/main/java/com/MtoM/MtoM/domain/qna/posts/dto/UpdatePostDTO.java
  src/main/java/com/MtoM/MtoM/domain/qna/posts/repository/PostRepository.java
  src/main/java/com/MtoM/MtoM/domain/qna/posts/service/PostRedisService.java
  src/main/java/com/MtoM/MtoM/domain/qna/posts/service/PostService.java
  src/main/java/com/MtoM/MtoM/domain/qna/selects/controller/SelectController.java
  src/main/java/com/MtoM/MtoM/domain/qna/selects/domain/SelectDomain.java
  src/main/java/com/MtoM/MtoM/domain/qna/selects/dto/CreateSelectDTO.java
  src/main/java/com/MtoM/MtoM/domain/qna/selects/dto/SelectWithCountsDTO.java
  src/main/java/com/MtoM/MtoM/domain/qna/selects/dto/VoteDTO.java
  src/main/java/com/MtoM/MtoM/domain/qna/selects/repository/SelectRepository.java
  src/main/java/com/MtoM/MtoM/domain/qna/selects/service/SelectRedisService.java
  src/main/java/com/MtoM/MtoM/domain/qna/selects/service/SelectService.java
  src/main/java/com/MtoM/MtoM/domain/user/controller/UserController.java
  src/main/java/com/MtoM/MtoM/domain/user/domain/UserDomain.java
  src/main/java/com/MtoM/MtoM/domain/user/service/UserService.java
  src/main/java/com/MtoM/MtoM/global/ResponseMessage.java
  src/main/java/com/MtoM/MtoM/global/S3Service/S3Service.java
  src/main/java/com/MtoM/MtoM/global/conifg/RedisConfig.java
  src/main/java/com/MtoM/MtoM/global/exception/error/ErrorCode.java
  src/main/java/com/MtoM/MtoM/global/exception/error/GlobalExceptionHandler.java
  src/main/resources/application.properties
  src/test/java/com/MtoM/MtoM/domain/qna/posts/controller/PostControllerTest.java
Labels: 🐞 Bugfix, 💡 Enhancement, ✨ Feature

#33 ✨ [Feat] (#7) QNA 게시물 댓글 생성, 수정, 삭제 API 구현
  .gitignore
  src/main/java/com/MtoM/MtoM/domain/qna/post_comment/controller/PostCommentController.java
  src/main/java/com/MtoM/MtoM/domain/qna/post_comment/dto/CreatePostComment.java
  src/main/java/com/MtoM/MtoM/domain/qna/post_comment/service/PostCommentService.java
  src/main/java/com/MtoM/MtoM/domain/user/controller/UserController.java
  src/main/java/com/MtoM/MtoM/domain/user/domain/UserDomain.java
  src/main/java/com/MtoM/MtoM/domain/user/service/UserService.java
  src/main/java/com/MtoM/MtoM/global/exception/error/ErrorCode.java
  src/main/java/com/MtoM/MtoM/global/exception/error/GlobalExceptionHandler.java
Labels: 🐞 Bugfix, ✨ Feature

#34 ✨ [Feat] (#7) QNA 양자택일 투표 redis로 기능 구현
  src/main/java/com/MtoM/MtoM/domain/qna/selects/controller/SelectController.java
  src/main/java/com/MtoM/MtoM/domain/qna/selects/service/SelectService.java
  src/main/java/com/MtoM/MtoM/domain/qna/selects/service/VoteService.java
Labels: ✨ Feature

#35 ✨️ [Feat] (#7) QNA 게시판 & 댓글 하트 누르기 기능 구현 완료
  src/main/java/com/MtoM/MtoM/domain/qna/posts/controller/PostCommentController.java
  src/main/java/com/MtoM/MtoM/domain/qna/posts/controller/PostController.java
  src/main/java/com/MtoM/MtoM/domain/qna/posts/dao/PostResponse.java
  src/main/java/com/MtoM/MtoM/domain/qna/posts/domain/PostCommentDomain.java
  src/main/java/com/MtoM/MtoM/domain/qna/posts/domain/PostDomain.java
  src/main/java/com/MtoM/MtoM/domain/qna/posts/dto/CreatePostComment.java
  src/main/java/com/MtoM/MtoM/domain/qna/posts/dto/UpdatePostComment.java
  src/main/java/com/MtoM/MtoM/domain/qna/posts/repository/PostCommentRepository.java
  src/main/java/com/MtoM/MtoM/domain/qna/posts/repository/PostRepository.java
  src/main/java/com/MtoM/MtoM/domain/qna/posts/service/PostCommentRedisService.java
  src/main/java/com/MtoM/MtoM/domain/qna/posts/service/PostCommentService.java
  src/main/java/com/MtoM/MtoM/domain/qna/posts/service/PostRedisService.java
  src/main/java/com/MtoM/MtoM/domain/qna/posts/service/PostService.java
  src/main/java/com/MtoM/MtoM/domain/qna/selects/service/SelectRedisService.java
Labels: 🔨Refactor, ✨ Feature

#36 ✨️ [Feat] (#7) QNA 게시판 상세페이지 API 구현 완료
  src/main/java/com/MtoM/MtoM/domain/qna/posts/controller/PostController.java
  src/main/java/com/MtoM/MtoM/domain/qna/posts/dao/CommentResponse.java
  src/main/java/com/MtoM/MtoM/domain/qna/posts/dao/PostResponse.java
  src/main/java/com/MtoM/MtoM/domain/qna/posts/dao/PostUserResponse.java
  src/main/java/com/MtoM/MtoM/domain/qna/posts/domain/PostDomain.java
  src/main/java/com/MtoM/MtoM/domain/qna/posts/repository/PostCommentRepository.java
  src/main/java/com/MtoM/MtoM/domain/qna/posts/service/PostRedisService.java
  src/main/java/com/MtoM/MtoM/domain/qna/posts/service/PostService.java
Labels: ✨ Feature

#37 ✨️ [Feat] (#7) QNA 게시판 HOT 댓글, 조회수, 하트수 API 구현 완료
  src/main/java/com/MtoM/MtoM/domain/qna/categroy/QnaController.java
  src/main/java/com/MtoM/MtoM/domain/qna/categroy/dao/QnaPostResponse.java
  src/main/java/com/MtoM/MtoM/domain/qna/categroy/dao/QnaSelectResponse.java
  src/main/java/com/MtoM/MtoM/domain/qna/categroy/dao/VoteOptionResponse.java
  src/main/java/com/MtoM/MtoM/domain/qna/categroy/service/QnaCategoryService.java
  src/main/java/com/MtoM/MtoM/domain/qna/posts/domain/PostDomain.java
  src/main/java/com/MtoM/MtoM/domain/qna/selects/domain/SelectDomain.java
  src/main/java/com/MtoM/MtoM/domain/qna/selects/service/VoteService.java
Labels: ✨ Feature

#38 ✨️ [Feat] (#7) QNA 게시판 하트 누른 유저 리스트 반환하는 API 구현 완료
  src/main/java/com/MtoM/MtoM/domain/qna/categroy/dao/QnaSelectResponse.java
  src/main/java/com/MtoM/MtoM/domain/qna/posts/controller/PostController.java
  src/main/java/com/MtoM/MtoM/domain/qna/posts/dao/PostHeartUsersResponse.java
  src/main/java/com/MtoM/MtoM/domain/qna/posts/service/PostRedisService.java
  src/main/java/com/MtoM/MtoM/domain/qna/posts/service/PostService.java
Labels: ✨ Feature

#42 ✨ [Feat] (#7) QNA 양자택일과 전체 게시판 조회 리스트 구현 완료
  src/main/java/com/MtoM/MtoM/domain/qna/categroy/QnaController.java
  src/main/java/com/MtoM/MtoM/domain/qna/categroy/dao/QnaSelectResponse.java
  src/main/java/com/MtoM/MtoM/domain/qna/categroy/dao/VoteOptionResponse.java
  src/main/java/com/MtoM/MtoM/domain/qna/categroy/service/QnaCategoryService.java
  src/main/java/com/MtoM/MtoM/domain/qna/selects/service/VoteService.java
Labels: ✨ Feature

#43 ♻️ [Refactor] (#29) User 관련 정보를 불러올 때 userId를 파라미터로 받도록 수정
  src/main/java/com/MtoM/MtoM/domain/user/UserController.java
  src/main/java/com/MtoM/MtoM/domain/user/service/UserService.java
Labels: 🔨Refactor

#44 ✨ [Feat] (#7) QNA 전체게시판 키워드 검색과 게시판 최신순 정렬 구현
  src/main/java/com/MtoM/MtoM/domain/qna/categroy/QnaController.java
  src/main/java/com/MtoM/MtoM/domain/qna/categroy/service/QnaCategoryService.java
Labels: ✨ Feature

#47 ✨ [Feat] (#7) QNA 게시판 댓글 좋아요 누른 사용자 조회 API 추가
  src/main/java/com/MtoM/MtoM/domain/qna/posts/controller/PostCommentController.java
  src/main/java/com/MtoM/MtoM/domain/qna/posts/service/PostCommentRedisService.java
  src/main/java/com/MtoM/MtoM/domain/qna/posts/service/PostCommentService.java
Labels: ✨ Feature

#51 ✨ [Feat] (#7) QNA 게시판 댓글 불러오기 API 추가
  src/main/java/com/MtoM/MtoM/domain/qna/categroy/QnaController.java
  src/main/java/com/MtoM/MtoM/domain/qna/posts/controller/PostController.java
  src/main/java/com/MtoM/MtoM/domain/qna/posts/dao/PostResponse.java
  src/main/java/com/MtoM/MtoM/domain/qna/posts/repository/PostCommentRepository.java
  src/main/java/com/MtoM/MtoM/domain/qna/posts/service/PostService.java
Labels: ✨ Feature

#54 ✨ [Feat] (#53) 유저가 작성한 QNA 게시판 조회 API 구현
  src/main/java/com/MtoM/MtoM/domain/qna/categroy/QnaController.java
  src/main/java/com/MtoM/MtoM/domain/qna/categroy/service/QnaCategoryService.java
  src/main/java/com/MtoM/MtoM/domain/qna/posts/repository/PostRepository.java
  src/main/java/com/MtoM/MtoM/domain/user/UserController.java
Labels: ✨ Feature
