Repository 2024-ITShow-MToM/MtoM-Back, pull requests merged in 2024-06, with the labels that each got.

#57 ✨ [Feat] (#13) 개인 채팅 서비스 구현
  build.gradle
  src/main/java/com/MtoM/MtoM/domain/chat/ChatController.java
  src/main/java/com/MtoM/MtoM/domain/chat/RedisMessagePublisher.java
  src/main/java/com/MtoM/MtoM/domain/chat/RedisMessageSubscriber.java
  src/main/java/com/MtoM/MtoM/domain/chat/WebSocketController.java
  src/main/java/com/MtoM/MtoM/domain/chat/domain/ChatMessage.java
  src/main/java/com/MtoM/MtoM/domain/chat/dto/ChatMessageDTO.java
  src/main/java/com/MtoM/MtoM/domain/chat/repository/ChatMessageRepository.java
  src/main/java/com/MtoM/MtoM/domain/chat/service/ChatMessageService.java
  src/main/java/com/MtoM/MtoM/global/conifg/RedisConfig.java
  src/main/java/com/MtoM/MtoM/global/conifg/WebSocketConfig.java
  src/main/java/com/MtoM/MtoM/global/conifg/WebSocketHandler.java
  src/main/resources/static/chat.html
Labels: ✨ Feature

#60 ♻️[Refactor] 코드 정리
  src/main/java/com/MtoM/MtoM/domain/chat/controller/ChatController.java
  src/main/java/com/MtoM/MtoM/domain/chat/controller/WebSocketController.java
  src/main/java/com/MtoM/MtoM/domain/chat/domain/ChatMessage.java
  src/main/java/com/MtoM/MtoM/domain/chat/repository/ChatMessageRepository.java
  src/main/java/com/MtoM/MtoM/domain/chat/service/RedisMessageSubscriber.java
  src/main/java/com/MtoM/MtoM/domain/posts/controller/PostCommentController.java
  src/main/java/com/MtoM/MtoM/domain/posts/controller/PostController.java
  src/main/java/com/MtoM/MtoM/domain/posts/dao/PostHeartUsersResponse.java
  src/main/java/com/MtoM/MtoM/domain/posts/domain/PostCommentDomain.java
  src/main/java/com/MtoM/MtoM/domain/posts/domain/PostDomain.java
  src/main/java/com/MtoM/MtoM/domain/posts/repository/PostCommentRepository.java
  src/main/java/com/MtoM/MtoM/domain/posts/repository/PostRepository.java
  src/main/java/com/MtoM/MtoM/domain/posts/service/PostCommentRedisService.java
  src/main/java/com/MtoM/MtoM/domain/posts/service/PostCommentService.java
  src/main/java/com/MtoM/MtoM/domain/posts/service/PostRedisService.java
  src/main/java/com/MtoM/MtoM/domain/posts/service/PostService.java
  src/main/java/com/MtoM/MtoM/domain/qna/categroy/QnaController.java
  src/main/java/com/MtoM/MtoM/domain/qna/categroy/service/QnaCategoryService.java
  src/main/java/com/MtoM/MtoM/domain/selects/controller/SelectController.java
  src/main/java/com/MtoM/MtoM/domain/selects/service/SelectService.java
  src/main/java/com/MtoM/MtoM/domain/selects/service/VoteService.java
  src/main/java/com/MtoM/MtoM/domain/user/service/UserService.java
  src/main/java/com/MtoM/MtoM/global/S3Service/S3Service.java
  src/main/java/com/MtoM/MtoM/global/conifg/RedisConfig.java
  src/main/java/com/MtoM/MtoM/global/conifg/WebConfig.java
  src/main/java/com/MtoM/MtoM/global/util/DateTimeUtils.java
Labels: 🔨Refactor

#63 🔀 user 관련 api 추가 개발
  src/main/java/com/MtoM/MtoM/domain/user/UserController.java
  src/main/java/com/MtoM/MtoM/domain/user/domain/SkillDomain.java
  src/main/java/com/MtoM/MtoM/domain/user/domain/UserDomain.java
  src/main/java/com/MtoM/MtoM/domain/user/dto/res/FindAllUserResponseDto.java
  src/main/java/com/MtoM/MtoM/domain/user/dto/res/FindByUserResponseDto.java
  src/main/java/com/MtoM/MtoM/domain/user/dto/res/SearchUserResponseDto.java
  src/main/java/com/MtoM/MtoM/domain/user/repository/UserRepository.java
  src/main/java/com/MtoM/MtoM/domain/user/service/UserService.java
Labels: ✨ Feature

#64 ✨[feat] 모든 채팅 참여자에 대한 알림 기능 구현
  src/main/java/com/MtoM/MtoM/domain/chat/controller/ChatController.java
  src/main/java/com/MtoM/MtoM/domain/chat/dto/ChatParticipantInfo.java
  src/main/java/com/MtoM/MtoM/domain/chat/repository/ChatMessageRepository.java
  src/main/java/com/MtoM/MtoM/domain/chat/service/ChatMessageService.java
Labels: ✨ Feature

#65 🐛[Fix] 채팅 마지막 메시지와 시간이 같은 오류 해결
  src/main/java/com/MtoM/MtoM/domain/chat/repository/ChatMessageRepository.java
  src/main/java/com/MtoM/MtoM/domain/chat/service/ChatMessageService.java
Labels: 🐞 Bugfix

#66 ✨[Feat] 알림 불러오기 API 구현 - 댓글 추가 했을 때
  src/main/java/com/MtoM/MtoM/domain/chat/controller/ChatController.java
  src/main/java/com/MtoM/MtoM/domain/chat/service/RedisMessagePublisher.java
  src/main/java/com/MtoM/MtoM/domain/notify/controller/NotifyController.java
  src/main/java/com/MtoM/MtoM/domain/notify/domain/NotificationType.java
  src/main/java/com/MtoM/MtoM/domain/notify/domain/Notify.java
  src/main/java/com/MtoM/MtoM/domain/notify/dto/NotifyResponseDTO.java
  src/main/java/com/MtoM/MtoM/domain/notify/repository/NotifyRepository.java
  src/main/java/com/MtoM/MtoM/domain/notify/service/NotificationRedisSubscriber.java
  src/main/java/com/MtoM/MtoM/domain/notify/service/NotifyService.java
  src/main/java/com/MtoM/MtoM/domain/notify/service/NotifyToStringConverter.java
  src/main/java/com/MtoM/MtoM/domain/posts/service/PostCommentService.java
  src/main/java/com/MtoM/MtoM/global/conifg/RedisConfig.java
  src/main/java/com/MtoM/MtoM/global/conifg/SinkConfig.java
  src/main/java/com/MtoM/MtoM/global/conifg/WebConfig.java
  src/main/java/com/MtoM/MtoM/global/message/NotifyMessage.java
Labels: ✨ Feature

#67 ✨[Feat] 게시물에 하트 눌렀을 때 알림가도록 추가
  src/main/java/com/MtoM/MtoM/domain/posts/service/PostRedisService.java
Labels: ✨ Feature

#68 🐛[Fix] 메시지 조회하는 부분 할 때 채팅방 전체의 마지막 메시지가 나오도록 수정
  src/main/java/com/MtoM/MtoM/domain/chat/repository/ChatMessageRepository.java
  src/main/java/com/MtoM/MtoM/domain/chat/service/ChatMessageService.java
Labels: 🐞 Bugfix, ✨ Feature

#74 ✨ [Fix] Query did not return a unique result: 3 results were returned 에러 해결
  src/main/java/com/MtoM/MtoM/domain/chat/repository/ChatMessageRepository.java
  src/main/java/com/MtoM/MtoM/domain/chat/service/ChatMessageService.java
Labels: 🐞 Bugfix
